import tkinter as tk 
win = tk.Tk()                
win.title("tk")              
win.resizable(False,False) 
e1 = tk.Label(win, bg="white", borderwidth=1, width=10, relief='groove') 
e1.grid(row=0, column=0, padx=5, pady=5)  
l2 = tk.Label(win, text="x", bg="white", borderwidth=1, width=1) 
l2.grid(row=0, column=1)  
e3 = tk.Label(win, bg="white", borderwidth=1, width=10, relief='groove') 
e3.grid(row=0, column=2, padx=5, pady=5) 
l4 = tk.Label(win, text="=", bg="white", borderwidth=1, width=1) 
l4.grid(row=0, column=3)   
e5 = tk.Label(win, bg="white", borderwidth=1, width=20, relief='groove') 
e5.grid(row=0, column=4, padx=5, pady=5)
